language: node_js

node_js:
  - "8.9.0"
  - "6"

cache:
  directories:
    - "node_modules"
    - "public"
git:
  depth: 3

branches:
  only:
  - dev
  - master
  
before_install:
  - npm i -g npm@5.5.1

install: npm install

before_script:
  - npm install -g mocha

script:
  - mocha spec mochaspec.js
